# Generated by Django 3.1.5 on 2021-01-14 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0002_auto_20210114_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='cloth_size',
            field=models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='shoe_size',
            field=models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], max_length=5, null=True),
        ),
    ]
