# Generated by Django 3.1.5 on 2021-01-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0002_auto_20210105_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cloth_type',
            field=models.CharField(choices=[('hat', 'Hat'), ('trousers', 'Trousers'), ('shirts', 'Shirts')], default='shirts', max_length=50),
        ),
    ]
