# Generated by Django 3.1.5 on 2021-01-12 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0002_auto_20210112_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sizes',
            new_name='Variant',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='price',
        ),
    ]
