# Generated by Django 3.1.5 on 2021-01-12 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0003_auto_20210112_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Variant',
        ),
        migrations.AddField(
            model_name='product',
            name='Variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop_api.productvariant'),
            preserve_default=False,
        ),
    ]
