# Generated by Django 3.1.5 on 2021-01-12 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0004_auto_20210112_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='colours',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='colours',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop_api.productcolour'),
            preserve_default=False,
        ),
    ]
