# Generated by Django 3.1.5 on 2021-01-13 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0005_auto_20210112_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Variant',
            new_name='variant',
        ),
    ]
