# Generated by Django 3.1.5 on 2021-01-19 11:43

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0006_auto_20210115_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=11, null=True, region=None),
        ),
    ]
