# Generated by Django 3.1.5 on 2021-01-13 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0006_auto_20210113_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
    ]
