# Generated by Django 3.1.5 on 2021-01-08 22:41

from django.db import migrations, models
import shop_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0006_auto_20210105_1905'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', shop_api.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
