# Generated by Django 3.1.5 on 2021-01-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0007_auto_20210108_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.IntegerField(default=1),
        ),
    ]
