# Generated by Django 3.1.5 on 2021-01-13 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0007_remove_product_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='colours',
        ),
        migrations.AddField(
            model_name='productcolour',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop_api.productvariant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop_api.product'),
            preserve_default=False,
        ),
    ]
