# Generated by Django 3.1.5 on 2021-01-13 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0008_auto_20210113_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcolour',
            old_name='variant',
            new_name='size',
        ),
    ]
