# Generated by Django 3.1.5 on 2021-01-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0009_auto_20210113_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolour',
            name='size',
        ),
        migrations.AddField(
            model_name='productcolour',
            name='size',
            field=models.ManyToManyField(to='shop_api.ProductVariant'),
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='variant',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='variant',
            field=models.ManyToManyField(to='shop_api.Product'),
        ),
    ]
