# Generated by Django 3.1.5 on 2021-01-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0010_auto_20210113_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolour',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='variant',
        ),
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.ManyToManyField(to='shop_api.ProductVariant'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='colours',
            field=models.ManyToManyField(to='shop_api.ProductColour'),
        ),
    ]
