# Generated by Django 3.1.5 on 2021-01-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0010_auto_20210123_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.ManyToManyField(to='shop_api.Address'),
        ),
    ]
