# Generated by Django 3.1.5 on 2021-01-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0011_auto_20210113_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='colours',
            new_name='colour',
        ),
    ]
